Less printing in job generation function (unless requested) Better variable naming in bash

diff --git a/src/test_download b/src/test_download
--- a/src/test_download
+++ b/src/test_download
@@ -8,21 +8,21 @@ jgi_password=""
 OPTIND=1
 while getopts "o:e:p:" opt; do
     case "$opt" in
-        o)  output_files=$OPTARG
+        o)  output_files="${OPTARG}"
             printf "output_files:   %s\n" "$output_files"
             ;;
-        e)  jgi_login=$OPTARG
+        e)  jgi_login="${OPTARG}"
             printf "jgi_login:      %s\n" "$jgi_login"
             ;;
-        p)  jgi_password=$OPTARG
+        p)  jgi_password="${OPTARG}"
             printf "jgi_password:   %s\n" "$jgi_password"
             ;;
         :)
-            echo "Option -$OPTARG requires an argument." >&2
+            printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
             exit 1
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2
+            printf "Invalid option: -%s\n" "${OPTARG}" >&2
             exit 1
             ;;
     esac
diff --git a/src/test_header b/src/test_header
--- a/src/test_header
+++ b/src/test_header
@@ -2,43 +2,64 @@
 
 set -e
 
-# how many CPUs?
-if [[ $SLURM_JOB_CPUS_PER_NODE ]]; then
-  maxCpus="$SLURM_JOB_CPUS_PER_NODE"
-  echo -e "[ $(date): Running with $maxCpus CPUs ]"
-else
-  maxCpus=1
-fi
-let "ram_limit = $maxCpus * 3000000000"
-echo -e "[ $(date): Allocating $((ram_limit/1000000000)) GB RAM ]"
+# bash traceback code from https://docwhat.org/tracebacks-in-bash/
+_showed_traceback=f
 
-# cleanup functions
-exit_error() {
-  echo -e "[ "$(date)": Script aborted ]"
-  exit 1
-}
-
-# catch exit codes
-trap_exit() {
-  exitCode=$?
-  if (( "exitCode" == 0 )) ; then
-    exit 0
-  else
-    exit_error
+_exit_trap () {
+  local _ec="$?"
+  if [[ $_ec != 0 && "${_showed_traceback}" != t ]]; then
+    traceback 1
   fi
 }
 
+_err_trap() {
+  local _ec="$?"
+  local _cmd="${BASH_COMMAND:-unknown}"
+  traceback 1
+  _showed_traceback=t
+  printf "The command %s exited with exit code %s.\n" "${_cmd}" "${_ec}" 1>&2
+}
+
+traceback() {
+  # Hide the traceback() call.
+  local -i start=$(( ${1:-0} + 1 ))
+  local -i end=${#BASH_SOURCE[@]}
+  local -i i=0
+  local -i j=0
+
+  printf "Traceback (last called is first):\n" 1>&2
+  for ((i=start; i < end; i++)); do
+    j=$(( i - 1 ))
+    local function="${FUNCNAME[$i]}"
+    local file="${BASH_SOURCE[$i]}"
+    local line="${BASH_LINENO[$j]}"
+    printf "     %s() in %s:%s\n" "${function}" in "${file}" "${line}" 1>&2
+  done
+}
+
 # traps
-trap exit_error SIGHUP SIGINT SIGTERM
-trap trap_exit EXIT
+trap _err_trap SIGHUP SIGINT SIGTERM
+trap _exit_trap EXIT
+trap _err_trap ERR
+
+# how many CPUs?
+if [[ "${SLURM_JOB_CPUS_PER_NODE}" ]]; then
+  max_cpus="${SLURM_JOB_CPUS_PER_NODE}"
+else
+  max_cpus=1
+fi
+ram_limit=$((max_cpus*3000000000))
+printf "[ %s: Running with %s CPU(s) ]\n" "$(date)" "${max_cpus}"
+printf "[ %s: Allocating %s GB RAM ]\n" "$(date)" $((ram_limit/1000000000))
 
 # handle waiting
 FAIL=0
 fail_wait() {
 for job in $(jobs -p); do
-  wait $job || let "FAIL+=1"
+  wait "${job}" || let "FAIL+=1"
 done
-if [[ ! "$FAIL" == 0 ]]; then
+if [[ ! "${FAIL}" == 0 ]]; then
+  printf "[ %s: Detected fail in background job ]\n" "$(date)"
   exit 1
 fi
 }
diff --git a/src/test_merge b/src/test_merge
--- a/src/test_merge
+++ b/src/test_merge
@@ -9,20 +9,20 @@ IF_N=0
 OF_N=0
 while getopts ":i:o:" opt; do
     case "$opt" in
-        i)  input_files[$IF_N]=$OPTARG
+        i)  ${input_files[${IF_N}]}="${OPTARG}"
             IF_N=$((IF_N + 1))
             printf "input_files:    %s\n" "${input_files[@]}"
             ;;
-        o)  output_files[$OF_N]=$OPTARG
+        o)  ${output_files[${OF_N}]}="${OPTARG}"
             OF_N=$((OF_N + 1))
             printf "output_files:   %s\n" "${output_files[@]}"
             ;;
         :)
-            echo "Option -$OPTARG requires an argument." >&2
+            printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
             exit 1
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2
+            printf "Invalid option: -%s\n" "${OPTARG}" >&2
             exit 1
             ;;
     esac
diff --git a/src/test_originate b/src/test_originate
--- a/src/test_originate
+++ b/src/test_originate
@@ -6,15 +6,15 @@ output_files=""
 OPTIND=1
 while getopts ":i:o:" opt; do
     case "$opt" in
-        o)  output_files=$OPTARG
-            printf "output_files:   %s\n" "$output_files"
+        o)  output_files="${OPTARG}"
+            printf "output_files:   %s\n" "${output_files}"
             ;;
         :)
-            echo "Option -$OPTARG requires an argument." >&2
+            printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
             exit 1
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2
+            printf "Invalid option: -%s\n" "${OPTARG}" >&2
             exit 1
             ;;
     esac
@@ -24,4 +24,4 @@ shift "$((OPTIND-1))"
 
 source "src/test_header"
 
-printf "%s" "$output_files" > "$output_files"
+printf "%s" "${output_files}" > "${output_files}"
